# Generated by Django 5.0.4 on 2024-04-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_feature_external_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='external_id',
        ),
        migrations.AddField(
            model_name='feature',
            name='type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feature',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
