# Generated by Django 5.0.4 on 2024-04-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_remove_feature_external_id_feature_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='external_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
